////////////////////////////////////////////////
///// GENERATED BY POCKETBASE : /models.ts /////
////////////////////////////////////////////////

import { AuthModelBase, ModelBase } from './models.base';

export interface _MfaModel extends ModelBase {
  id: string;
  collectionRef: string;
  recordRef: string;
  method: string;
}

export interface _OtpModel extends ModelBase {
  id: string;
  collectionRef: string;
  recordRef: string;
  password: string;
  sentTo?: string;
}

export interface _ExternalAuthModel extends ModelBase {
  id: string;
  collectionRef: string;
  recordRef: string;
  provider: string;
  providerId: string;
}

export interface _AuthOriginModel extends ModelBase {
  id: string;
  collectionRef: string;
  recordRef: string;
  fingerprint: string;
}

export interface _SuperuserModel extends AuthModelBase {
  id: string;
  password: string;
  tokenKey: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
}

export interface _UserModel extends AuthModelBase {
  id: string;
  password: string;
  tokenKey: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: File | Blob | string;
  writers?: any;
  readers?: any;
}

export interface _ContentModel extends ModelBase {
  id: string;
  public?: boolean;
  key?: string;
  title?: string;
  type?: '' | 'empty' | 'form' | 'table' | 'html' | 'playlist' | 'hiboutik' | 'odoo';
  data?: any;
  files?: File | Blob | string;
  medias?: string[];
  group?: string;
}

export interface _DeviceModel extends ModelBase {
  id: string;
  online?: Date | string;
  key?: string;
  name?: string;
  info?: any;
  action?: string;
  input?: string;
  result?: any;
  capture?: File | Blob | string;
  files?: File | Blob | string;
  media?: string;
  user?: string;
  group?: string;
}

export interface _GroupModel extends ModelBase {
  id: string;
  key?: string;
  name?: string;
  plugins?: '' | 'hiboutik';
  user?: string;
}

export interface _JobModel extends ModelBase {
  id: string;
  action?: '' | 'test' | 'test2' | 'addMember' | 'convert';
  status?: '' | 'pending' | 'processing' | 'finished' | 'failed' | 'deleted' | 'claimed' | 'created';
  progress?: number;
  error?: string;
  input?: any;
  result?: any;
  logs?: string;
  files?: File | Blob | string;
  media?: string;
  group?: string;
}

export interface _MediaModel extends ModelBase {
  id: string;
  generated?: Date | string;
  key?: string;
  title?: string;
  desc?: string;
  type?: '' | 'folder' | 'playlist' | 'pdf' | 'image' | 'video' | 'unknown';
  mime?: string;
  bytes?: number;
  width?: number;
  height?: number;
  seconds?: number;
  data?: any;
  source?: File | Blob | string;
  variants?: File | Blob | string;
  parent?: string;
  user?: string;
  group?: string;
}

export interface _MemberModel extends ModelBase {
  id: string;
  role?: number;
  desc?: string;
  email?: string;
  user?: string;
  group?: string;
  device?: string;
}

export interface _ApplicationModel extends ModelBase {
  id: string;
  name?: string;
  version?: string;
  active?: boolean;
  file?: File | Blob | string;
}

export interface _LockModel extends ModelBase {
  id: string;
  seconds?: number;
  key?: string;
  group?: string;
}

export interface _LogModel extends ModelBase {
  id: string;
  level?: '' | 'debug' | 'info' | 'warn' | 'error';
  message?: string;
  ip?: string;
  data?: any;
  user?: string;
  group?: string;
}
